#!/bin/sh

set -o errexit

/usr/lib/balena/balena-set-scheduling-prio 0 rr 35
/usr/lib/balena-supervisor/balena-supervisor-set-scheduling-prio 0 rr 10

sleep 10

/usr/lib/balena/balena-set-scheduling-prio 0 rr 35
/usr/lib/balena-supervisor/balena-supervisor-set-scheduling-prio 0 rr 10
