#!/bin/sh

sleepSecs="$1"
policy="$2"
prio="$3"

sleep "$sleepSecs"

pids=$(balena top balena_supervisor -eo pid)

if [ $? != 0 ]; then
	exit 0
fi

pids=$(echo $pids | tail -n +2)

for pid in $pids; do
	chrt --$policy --all-tasks --reset-on-fork --pid $prio $pid
done
